name: data_engineering
version: "1.0.0"
config-version: 2

profile: data_engineering        

# paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"     
clean-targets: ["target", "dbt_packages"]


models:
  data-engineering:

    core:
      views:
        +materialized: view
      tables:
        +materialized: table
        +as_columnstore: False
      ephemeral:
        +materialized: ephemeral