data_engineering:
  outputs:
    dev:
      dataset: crypto_dataset
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /opt/airflow/secrets/gcp-key.json
      location: EU
      method: service-account
      priority: interactive
      project: 'terraform-sylvia'
      threads: 6
      type: bigquery
  target: dev
